version: '3.2'
networks:
  airflow:

services:
  postgres:
    image: postgres:11.5
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_DB=airflow
      - POSTGRES_PASSWORD=airflow
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./test_env/database/data:/var/lib/postgresql/data/pgdata
      - ./test_env/database/logs:/var/lib/postgresql/data/log
    command: >
      postgres
        -c listen_addresses=*
        -c logging_collector=on
        -c log_destination=stderr
        -c max_connections=200
    networks:
      - airflow
  initdb:
    image: apache/airflow
    env_file:
      - env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./test_env/logs:/opt/airflow/logs
      - ./test_env/files:/opt/airflow/files
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: /bin/bash
    command: -c "airflow initdb && airflow pool -s bigquery 1 bigquery_connections"
    depends_on:
      - postgres
    networks:
      - airflow