version: '3.2'
networks:
  airflow:

services:
  postgres:
    image: postgres:11.5
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_DB=airflow
      - POSTGRES_PASSWORD=airflow
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./test_env/database/data:/var/lib/postgresql/data/pgdata
      - ./test_env/database/logs:/var/lib/postgresql/data/log
    command: >
      postgres
        -c listen_addresses=*
        -c logging_collector=on
        -c log_destination=stderr
        -c max_connections=200
    networks:
      - airflow

  webserver:
    env_file:
      - env
    image: apache/airflow
    ports:
      - 8080:8080
    volumes:
      - ./dags:/opt/airflow/dags
      - ./test_env/logs:/opt/airflow/logs
      - ./test_env/files:/opt/airflow/files
      - ./test_env/credentials:/credentials
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - postgres
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /opt/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - airflow

  scheduler:
    image: apache/airflow
    env_file:
      - env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./test_env/logs:/opt/airflow/logs
      - ./test_env/files:/opt/airflow/files
      - ./test_env/credentials:/credentials
      - /var/run/docker.sock:/var/run/docker.sock
    command: scheduler
    networks:
      - airflow